articles/urls.py
from django.urls import path

from .views import ArticleView, ArticleListView, FavoriteArticleView, PostCommentView

app_name = 'articles'

urlpatterns = [
    path('', ArticleListView.as_view(), name='articles'),
    path('<int:pk>', ArticleView.as_view(), name='article'),
    path('<int:pk>/comments', PostCommentView.as_view(), name='comments'),
    path('<int:pk>/favorite', FavoriteArticleView.as_view(), name='favorite'),
]

authenticate/urls.py
from django.urls import path
from .views import LoginView, LogoutView, RegisterView

app_name = 'authenticate'

urlpatterns = [
    path('login', LoginView.as_view(), name='login'),
    path('logout', LogoutView.as_view(), name='logout'),
    path('register', RegisterView.as_view(), name='register')
]

settings/urls.py
from django.urls import path

from .views import UpdateUsernameView, UpdateEmailView, UpdateFolloweeView, \
    UpdateFollowerView, UpdatePasswordView, CreateArticleView, \
    PostedArticleListView, UpdateArticleView, UpdateProfileView, \
    DeleteUserView, DeleteArticleView

app_name = 'settings'

urlpatterns = [
    path('username', UpdateUsernameView.as_view(), name='username'),
    path('email', UpdateEmailView.as_view(), name='email'),
    path('followees', UpdateFolloweeView.as_view(), name='followees'),
    path('followers', UpdateFollowerView.as_view(), name='followers'),
    path('password', UpdatePasswordView.as_view(), name='password'),
    path('profile', UpdateProfileView.as_view(), name='profile'),
    path('newarticle', CreateArticleView.as_view(), name='newarticle'),
    path('postedarticles', PostedArticleListView.as_view(), name='postedarticles'),
    path('postedarticles/<int:pk>', UpdateArticleView.as_view(), name='updatearticle'),
    path('postedarticles/<int:pk>/delete', DeleteArticleView.as_view(), name='deletearticle'),
    path('delete-user', DeleteUserView.as_view(), name='deleteuser')
]

users/urls.py
from django.urls import path
from .views import PostedArticleListView, FavoriteListView, FolloweeListView, FollowerListView, FollowView

app_name = 'users'

urlpatterns = [
    path('<str:username>', PostedArticleListView.as_view(), name='articles'),
    path('<str:username>/favorites', FavoriteListView.as_view(), name='favorites'),
    path('<str:username>/followees', FolloweeListView.as_view(), name='followees'),
    path('<str:username>/followers', FollowerListView.as_view(), name='followers'),
    path('<str:username>/follow', FollowView.as_view(), name='follow'),
]

templates/base/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ja">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
        <link rel="stylesheet" href="{% static 'base/base.css'%}">
        {% block extra_header %}{% endblock %}
        <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
        <title>simple blog</title>    
    </head>

    <body>
        <header>
            <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
                <a class="navbar-brand" href="{% url 'articles:articles' %}">simple blog</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarNav">
                    <ul class="navbar-nav">
                        <li class="nav-item">
                            {% if user.is_authenticated %}
                                <a class="nav-link" href="{% url 'authenticate:logout' %}">logout</a>
                            {% else %}
                                <a class="nav-link" href="{% url 'authenticate:login' %}">login</a>
                            {% endif %}
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'authenticate:register' %}">register</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'settings:username' %}">settings</a>
                        </li>
                    </ul>
                </div>
            </nav>
        </header>

        {% block content %}
        {% endblock %}
    </body>

</html>