articles/urls.py
from django.urls import path

from .views import ArticleView, ArticleListView, FavoriteArticleView, PostCommentView

app_name = 'articles'

urlpatterns = [
    path('', ArticleListView.as_view(), name='articles'),
    path('<int:pk>', ArticleView.as_view(), name='article'),
    path('<int:pk>/comments', PostCommentView.as_view(), name='comments'),
    path('<int:pk>/favorite', FavoriteArticleView.as_view(), name='favorite'),
]

settings/urls.py
from django.urls import path

from .views import UpdateUsernameView, UpdateEmailView, UpdateFolloweeView, \
    UpdateFollowerView, UpdatePasswordView, CreateArticleView, \
    PostedArticleListView, UpdateArticleView, UpdateProfileView, \
    DeleteUserView, DeleteArticleView

app_name = 'settings'

urlpatterns = [
    path('username', UpdateUsernameView.as_view(), name='username'),
    path('email', UpdateEmailView.as_view(), name='email'),
    path('followees', UpdateFolloweeView.as_view(), name='followees'),
    path('followers', UpdateFollowerView.as_view(), name='followers'),
    path('password', UpdatePasswordView.as_view(), name='password'),
    path('profile', UpdateProfileView.as_view(), name='profile'),
    path('newarticle', CreateArticleView.as_view(), name='newarticle'),
    path('postedarticles', PostedArticleListView.as_view(), name='postedarticles'),
    path('postedarticles/<int:pk>', UpdateArticleView.as_view(), name='updatearticle'),
    path('postedarticles/<int:pk>/delete', DeleteArticleView.as_view(), name='deletearticle'),
    path('delete-user', DeleteUserView.as_view(), name='deleteuser')
]

users/urls.py
from django.urls import path
from .views import PostedArticleListView, FavoriteListView, FolloweeListView, FollowerListView, FollowView

app_name = 'users'

urlpatterns = [
    path('<str:username>', PostedArticleListView.as_view(), name='articles'),
    path('<str:username>/favorites', FavoriteListView.as_view(), name='favorites'),
    path('<str:username>/followees', FolloweeListView.as_view(), name='followees'),
    path('<str:username>/followers', FollowerListView.as_view(), name='followers'),
    path('<str:username>/follow', FollowView.as_view(), name='follow'),
]

articles/models.py
import datetime
from django.db import models
from django.contrib.auth import get_user_model

# Create your models here.

User = get_user_model()


class Tag(models.Model):
    tag = models.CharField(max_length=100, blank=False, null=False, unique=True)

    def __str__(self):
        return self.tag


class Article(models.Model):
    author = models.ForeignKey(User,
                               on_delete=models.CASCADE,
                               related_name='my_articles')
    title = models.CharField(max_length=1000)
    content = models.TextField(max_length=10000)
    create_date = models.DateField(default=datetime.date.today)
    tags = models.ManyToManyField(Tag, related_name='tagged_articles')
    favorite_users = models.ManyToManyField(User,
                                            blank=True,
                                            related_name='favorited_aritcles')

    class Meta:
        ordering = ['-create_date']

    def __str__(self):
        return self.title

    def is_favorited(self, user):
        """
        Userオブジェクトである引数userが記事をお気に入りに登録しているか否かの状態を返す

        Parameters
        ----------
        user : User
            お気に入りしているユーザ(favaorite_users)の中に含まれているか確認する対象

        Raises
        ------
        TypeError
            userオブジェクトがUserクラスのインスタンスで無い場合に発生

        Returns
        -------
        False : bool
            userが認証されていないユーザの場合もしくは,favorite_usersに含まれていない場合

        True : bool
            userが認証されており,かつfavorite_usersに含まれている
        """
        if (not user.is_authenticated
                or not self.favorite_users.filter(pk=user.pk).exists()):
            return False
        return True


class Comment(models.Model):
    article = models.ForeignKey(Article, on_delete=models.CASCADE)
    comment_author = models.ForeignKey(User, on_delete=models.CASCADE)
    content = models.TextField(max_length=1000)
    create_data = models.DateField(auto_now_add=True)

    def __str__(self):
        return 'comment by {} at {}'.format(self.comment_author,
                                            self.create_data)

authenticate/models.py
from django.apps import apps
from django.contrib.auth.hashers import make_password
from django.core.exceptions import ObjectDoesNotExist
from django.db import models
from django.core.mail import send_mail
from django.contrib.auth.models import PermissionsMixin, UserManager
from django.contrib.auth.base_user import AbstractBaseUser
from django.db.models.deletion import CASCADE
from django.utils.translation import gettext_lazy as _
from django.utils import timezone
from django.contrib.auth.validators import UnicodeUsernameValidator
from django.urls.base import reverse


class UserManager(UserManager):
    use_in_migrations = True

    def _create_user(self, username, email, password, **extra_fields):
        """
        Create and save a user with the given username, email, and password.
        """
        if not username:
            raise ValueError('The given username must be set')
        if not email:
            raise ValueError('The given email must be set')
        email = self.normalize_email(email)
        # Lookup the real model class from the global app registry so this
        # manager method can be used in migrations. This is fine because
        # managers are by definition working on the real model.
        GlobalUserModel = apps.get_model(self.model._meta.app_label, self.model._meta.object_name)
        username = GlobalUserModel.normalize_username(username)
        user = self.model(username=username, email=email, **extra_fields)
        user.password = make_password(password)
        user.save(using=self._db)
        return user


class User(AbstractBaseUser, PermissionsMixin):
    """
    An abstract base class implementing a fully featured User model with
    admin-compliant permissions.
    Username and password are required. Other fields are optional.
    """
    username_validator = UnicodeUsernameValidator()

    username = models.CharField(
        _('username'),
        max_length=30,
        unique=True,
        help_text=_('Required. 30 characters or fewer. Letters, digits and @/./+/-/_ only.'),
        validators=[username_validator],
        error_messages={
            'unique': _("A user with that username already exists."),
        },
    )
    email = models.EmailField(_('email address'), unique=True)
    first_name = models.CharField(_('first name'), max_length=150, blank=True)
    last_name = models.CharField(_('last name'), max_length=150, blank=True)
    icon = models.ImageField(_('user icon'), upload_to='media/images', default='media/images/default.png')
    profile_message = models.TextField(_('user profile message'), max_length=1000, blank=True)
    followers = models.ManyToManyField('User', through='Relation', through_fields=('followee', 'follower'), related_name='+')
    followees = models.ManyToManyField('User', through='Relation', through_fields=('follower', 'followee'), related_name='+')
    is_staff = models.BooleanField(
        _('staff status'),
        default=False,
        help_text=_('Designates whether the user can log into this admin site.'),
    )
    is_active = models.BooleanField(
        _('active'),
        default=True,
        help_text=_(
            'Designates whether this user should be treated as active. '
            'Unselect this instead of deleting accounts.'
        ),
    )
    date_joined = models.DateTimeField(_('date joined'), default=timezone.now)

    objects = UserManager()

    EMAIL_FIELD = 'email'
    USERNAME_FIELD = 'username'
    REQUIRED_FIELDS = ['email']

    class Meta:
        verbose_name = _('user')
        verbose_name_plural = _('users')

    def clean(self):
        super().clean()
        self.email = self.__class__.objects.normalize_email(self.email)

    def get_full_name(self):
        """
        Return the first_name plus the last_name, with a space in between.
        """
        full_name = '%s %s' % (self.first_name, self.last_name)
        return full_name.strip()

    def get_short_name(self):
        """Return the short name for the user."""
        return self.first_name

    def email_user(self, subject, message, from_email=None, **kwargs):
        """Send an email to this user."""
        send_mail(subject, message, from_email, [self.email], **kwargs)

    def get_absolute_url(self):
        return reverse('register:register')

    def is_follow(self, followee):
        # 型チェック
        if not isinstance(followee, User):
            raise TypeError('followee or followee is not User')

        # followerがfolloweeをフォローしているRelationモデルが存在するか確認する
        try:
            self.followees.get(pk=followee.pk)
        except ObjectDoesNotExist:
            return False

        return True


class Relation(models.Model):
    # フォローする側
    follower = models.ForeignKey(User, on_delete=CASCADE, related_name='followee_relations')
    # フォローされる側
    followee = models.ForeignKey(User, on_delete=CASCADE, related_name='follower_relations')

    class Meta:
        unique_together = ('follower', 'followee')

settings/models.py
from django.db import models

# Create your models here.

articles/forms.py
from django import forms
from django.contrib.auth import get_user_model

from .models import Comment, Tag

User = get_user_model()


class SearchArticleForm(forms.Form):
    keyword = forms.CharField(max_length=100, required=False)

    all_article_tag = Tag.objects.order_by('pk').all()
    TAG_CHOICES = [(article_tag.pk, article_tag.tag)
                   for article_tag in all_article_tag]
    TAG_CHOICES.insert(0, ('all', '全てのタグ'))
    tag = forms.ChoiceField(choices=TAG_CHOICES, required=False)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs['class'] = 'form-control'


class PostCommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('content',)
        widgets = {
            'content': forms.Textarea(attrs={'rows': 5, 'cols': 30}),
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs['class'] = 'mt-2 mb-3 font-weight-normal'


class FavoriteArticleForm(forms.Form):
    """
    記事をお気にいりに登録する際にユーザ名を送信するためのフォーム

    Parameters
    ----------
    username : str
        ユーザ名を表す文字列
    """
    username = forms.CharField(max_length=30, required=True)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['username'].widget = forms.HiddenInput()

    def clean_username(self):
        username = self.cleaned_data['username']

        # ユーザ名に一致するユーザが存在しない場合はバリデーションエラーを発生させる
        if not User.objects.filter(username=username).exists():
            raise forms.ValidationError("user is not exist")

        return username

articles/views.py
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.exceptions import ObjectDoesNotExist
from django.db.models import Q
from django.http import Http404, HttpResponseBadRequest
from django.http.response import JsonResponse
from django.shortcuts import get_object_or_404, redirect
from django.views.generic import FormView, CreateView, DetailView, ListView
from django.shortcuts import render


from users.forms import FollowForm
from .forms import FavoriteArticleForm, PostCommentForm, SearchArticleForm
from .models import Article, Tag

# Create your views here.

User = get_user_model()


class ArticleListView(ListView):
    template_name = 'articles/articles.html'
    model = Article
    paginate_by = 5

    def fetch_get_parameter(self, parameter_name):
        if type(parameter_name) is not str or parameter_name == "":
            raise KeyError("request url is not include {}".format(parameter_name))

        if parameter_name not in self.request.GET:
            raise KeyError("request url is not include {}".format(parameter_name))

        return self.request.GET.get(parameter_name)

    def get_queryset(self):
        queryset = super().get_queryset()

        # キーワードをURLパラメータから抽出
        try:
            keyword = self.fetch_get_parameter("keyword")
            queryset = queryset.filter(Q(title__contains=keyword)
                                       | Q(content__contains=keyword))
        except KeyError:
            pass

        # tagをURLパラメータから抽出
        try:
            tag_pk = self.fetch_get_parameter("tag")
        except KeyError:
            # タグが存在しない場合は現時点での条件のクエリセットを返す
            return queryset

        # tagがallである場合は現時点でのクエリセットを返す
        if tag_pk == 'all':
            return queryset

        # タグオブジェクトを取得する
        # 存在しないタグの場合は,存在しないタグのpkを指定したクエリセットを返す
        try:
            tag = Tag.objects.get(pk__in=tag_pk)
        except ValueError:
            queryset = queryset.filter(tags=-1)
            return queryset
        except ObjectDoesNotExist:
            queryset = queryset.filter(tags=-1)
            return queryset

        queryset = queryset.filter(tags=tag)
        return queryset

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        # 記事一覧を取得する,検索結果が何も無い場合は 404 を返す
        article_list = context['article_list']
        if article_list.first() is None:
            raise Http404('指定したキーワードとタグを含む記事は存在しませんでした')

        context['form'] = SearchArticleForm
        return context


class ArticleView(DetailView):
    template_name = 'articles/article.html'
    model = Article

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        context['comment_form'] = PostCommentForm

        context['favorite_form'] = FavoriteArticleForm
        # 既にお気に入り登録しているか否かでボタンに表示する値ととお気に入りフォームのvalue
        # に設定される状態を示す文字列を決定する
        context['favorite_button_value'] = 'お気に入り済み' \
            if self.object.is_favorited(self.request.user) else 'お気に入りに追加'
        context['favorite_status'] = 'favorited' \
            if self.object.is_favorited(self.request.user) else 'notfavorited'

        # 認証されていないユーザの場合は現時点のデータを返す
        if not self.request.user.is_authenticated:
            return context

        # 認証ユーザの場合はFavoriteArticleFormに現在のユーザ名を設定
        username = self.request.user.username
        initial_form_dict = dict(follower=username)
        follow_form = FollowForm(initial=initial_form_dict)
        context['follow_form'] = follow_form

        return context

    def get(self, request, *args, **kwargs):
        if not self.request.user.is_authenticated:
            return super().get(request, *args, **kwargs)

        # 認証ユーザの場合はFavoriteArticleFormに現在のユーザ名を設定
        username = self.request.user.username
        initial_form_dict = dict(username=username)
        favorite_form = FavoriteArticleForm(request.GET or None,
                                            initial=initial_form_dict)
        self.object = self.get_object()
        context = self.get_context_data(object=self.object)
        context['favorite_form'] = favorite_form

        return render(request, self.template_name, context)


class PostCommentView(LoginRequiredMixin, CreateView):
    template_name = ''
    form_class = PostCommentForm

    def form_valid(self, form):
        article_id = self.kwargs['pk']
        article = get_object_or_404(Article, pk=article_id)
        author = User.objects.get(pk=self.request.user.pk)

        comment = form.save(commit=False)
        comment.article = article
        comment.comment_author = author
        comment.save()
        return redirect('articles:article', pk=article_id)

    # GETリクエストされた場合はとりあえずリダイレクトさせる
    def get(self, request, *args, **kwargs):
        article_id = self.kwargs['pk']
        return redirect('articles:article', pk=article_id)


class FavoriteArticleView(LoginRequiredMixin, FormView):
    form_class = FavoriteArticleForm
    template_name = 'base/blank.html'

    def post(self, request, *args, **kwargs):
        form = self.get_form()
        if form.is_valid():
            return self.form_valid(form)
        else:
            return self.form_invalid(form)

    def form_valid(self, form):
        # Ajaxリクエストでない場合はBadRequestを返す
        if not self.request.is_ajax:
            raise HttpResponseBadRequest()

        # 送信されてきたユーザ名を取得し,送信してきたユーザと同じであるか確認する
        username = form.cleaned_data['username']
        user = User.objects.get(username=username)
        if self.request.user != user:
            raise HttpResponseBadRequest()

        # 更新対象のArticleオブジェクトを取得
        article_id = self.kwargs['pk']
        article = get_object_or_404(Article, pk=article_id)

        # お気に入りユーザとして登録していない場合は追加を行い,
        # 既にお気に入りユーザとして登録している場合は削除を行い,状態を保存して更新する
        if article.favorite_users.filter(username=username).exists():
            article.favorite_users.remove(user)
            status = 'notfavorited'
        else:
            article.favorite_users.add(user)
            status = 'favorited'
        article.save()

        # 処理の結果を格納するJSONオブジェクトを返す
        json_response = {
            'data': {
                'status': status
            }
        }
        return JsonResponse(json_response)

    def form_invalid(self, form):
        # 正しく無いデータが送信されてきた場合は500を返す
        return JsonResponse({}, status=500)

templates/settings/articles.html
{% extends 'base/base.html' %}
{% load static %}

{% block extra_header %}
    <link rel="stylesheet" href="{% static 'settings/links.css' %}">
    <link rel="stylesheet" href="{% static 'settings/articles.css' %}">
{% endblock %}

{% block content %}
    <div class="settings-entire">
        {% include 'settings/links.html' %}

        <div class="posted-articles">
            {% if article_list %}
                <ul>
                    {% for article in article_list %}
                        <ul class="article">
                            <li class="author-info">{{ article.create_date }}に投稿</li>
                            <li class="article-title"><a href="{% url 'settings:updatearticle' article.pk %}"> {{ article.title }} </a></li>
                            <li class="article-content">{{ article.content|slice:":30" }} ... </li>
                        </ul>
                    {% endfor %}
                </ul>

                <ul class="pagination">
                    {% if page_obj.has_previous %}
                        <li class="page-item">
                            <a class="page-link" href="?page={{ page_obj.previous_page_number }}">
                                <span aria-hidden="true">&laquo;</span>
                            </a>
                        </li>
                    {% endif %}

                    {% for num in page_obj.paginator.page_range %}
                        {% if page_obj.number == num %}
                            <li class="page-item active"><a class="page-link" href="#!">{{ num }}</a></li>
                        {% else %}
                            <li class="page-item"><a class="page-link" href="?page={{ num }}">{{ num }}</a></li>
                        {% endif %}
                    {% endfor %}
                
                    {% if page_obj.has_next %}
                        <li class="page-item">
                            <a class="page-link" href="?page={{ page_obj.next_page_number }}">
                                <span aria-hidden="true">&raquo;</span>
                            </a>
                        </li>
                    {% endif %}
                </ul>
            {% else %}
                まだ記事を投稿していません。
            {% endif %}
        </div>
    </div>
{% endblock %}

templates/settings/followee.html
{% extends 'base/base.html' %}
{% load static %}

{% block extra_header %}
<link rel="stylesheet" href="{% static 'settings/followee.css' %}">
<link rel="stylesheet" href="{% static 'settings/links.css' %}">
<script src="https://code.jquery.com/jquery-3.6.0.js" integrity="sha256-H+K7U5CnXl1h5ywQfKtSj8PCmoN9aaq30gDh27Xc0jk=" crossorigin="anonymous" defer></script>
<script src="{% static 'users/follow.js' %}" defer></script>
{% endblock %}

{% block content %}
    <div class="settings-entire">
        <div class="settings-sidebar">
            {% include 'settings/links.html' %}
        </div>

        <div class="main-contents">
            <div class="followees">
                {% for relation in relation_list %}
                    <div class="followee">
                        <ul>
                            <li class="followee-icon"><img src="{{ MEDIA_URL }}{{ relation.followee.icon }}" style="border-radius: 50px; width: 25px; height: 25px;"></li>
                            <li class="followee-username"><a href="{% url 'users:articles' relation.followee.username %}"> {{ relation.followee.username }} </a></li>

                            {% if user.is_authenticated and user.username != relation.followee.username %}
                                {% load is_follow %}
                                {% is_follow user relation.followee as follow_status %}
                                <form name="follow" action="{% url 'users:follow' relation.followee.username %}" method="POST">
                                    {% csrf_token %}
                                    {{ follow_form.follower }}
                                    {% if follow_status %}
                                        <input class="btn btn-info" name="follow_button" type="submit" value="フォロー中"/>
                                    {% else %}
                                        <input class="btn btn-info" name="follow_button" type="submit" value="フォローする"/>
                                    {% endif %}
                                </form>
                            {% endif %}

                            <li class="followee-profile"> {{ relation.followee.profile_message|slice:":30" }}... </li>
                        </ul>
                    </div>
                {% endfor %}
            </div>
        </div>
    </div>

    {% if relation_list %}
        <div class="pagination">
            <ul class="pagination">
                {% if page_obj.has_previous %}
                    <li class="page-item">
                        <a class="page-link" href="?page={{ page_obj.previous_page_number }}">
                            <span aria-hidden="true">&laquo;</span>
                        </a>
                    </li>
                {% endif %}
            
                {% for num in page_obj.paginator.page_range %}
                    {% if page_obj.number == num %}
                        <li class="page-item active"><a class="page-link" href="#!">{{ num }}</a></li>
                    {% else %}
                        <li class="page-item"><a class="page-link" href="?page={{ num }}">{{ num }}</a></li>
                    {% endif %}
                {% endfor %}
            
                {% if page_obj.has_next %}
                    <li class="page-item">
                        <a class="page-link" href="?page={{ page_obj.next_page_number }}">
                            <span aria-hidden="true">&raquo;</span>
                        </a>
                    </li>
                {% endif %}
            </ul> 
        </div>
    {% endif %}
{% endblock %}

templates/settings/follower.html
{% extends 'base/base.html' %}
{% load static %}

{% block extra_header %}
<link rel="stylesheet" href="{% static 'settings/links.css' %}">
<link rel="stylesheet" href="{% static 'settings/follower.css' %}">
<script src="https://code.jquery.com/jquery-3.6.0.js" integrity="sha256-H+K7U5CnXl1h5ywQfKtSj8PCmoN9aaq30gDh27Xc0jk=" crossorigin="anonymous" defer></script>
<script src="{% static 'users/follow.js' %}" defer></script>
{% endblock %}

{% block content %}
    <div class="settings-entire">
        <div class="settings-sidebar">
            {% include 'settings/links.html' %}
        </div>

        <div class="main-contents">
            <div class="followers">
                {% for relation in relation_list %}
                    <div class="follower">
                        <ul>
                            <li class="follower-icon"><img src="{{ MEDIA_URL }}{{ relation.follower.icon }}" style="border-radius: 50px; width: 25px; height: 25px;"></li>
                            <li class="follower-username"><a href="{% url 'users:articles' relation.follower.username %}"> {{ relation.follower.username }} </a></li>

                            {% if user.is_authenticated and user.username != relation.follower.username %}
                                {% load is_follow %}
                                {% is_follow user relation.follower as follow_status %}
                                <form name="follow" action="{% url 'users:follow' relation.follower.username %}" method="POST">
                                    {% csrf_token %}
                                    {{ follow_form.follower }}
                                    {% if follow_status %}
                                        <input class="btn btn-info" name="follow_button" type="submit" value="フォロー中"/>
                                    {% else %}
                                        <input class="btn btn-info" name="follow_button" type="submit" value="フォローする"/>
                                    {% endif %}
                                </form>
                            {% endif %}

                            <li class="follower-profile"> {{ relation.follower.profile_message|slice:":30" }}... </li>
                        </ul>
                    </div>
                {% endfor %}
            </div>
        </div>
    </div>

    {% if relation_list %}
        <div class="pagination">
            <ul class="pagination">
                {% if page_obj.has_previous %}
                    <li class="page-item">
                        <a class="page-link" href="?page={{ page_obj.previous_page_number }}">
                            <span aria-hidden="true">&laquo;</span>
                        </a>
                    </li>
                {% endif %}
            
                {% for num in page_obj.paginator.page_range %}
                    {% if page_obj.number == num %}
                        <li class="page-item active"><a class="page-link" href="#!">{{ num }}</a></li>
                    {% else %}
                        <li class="page-item"><a class="page-link" href="?page={{ num }}">{{ num }}</a></li>
                    {% endif %}
                {% endfor %}
            
                {% if page_obj.has_next %}
                    <li class="page-item">
                        <a class="page-link" href="?page={{ page_obj.next_page_number }}">
                            <span aria-hidden="true">&raquo;</span>
                        </a>
                    </li>
                {% endif %}
            </ul> 
        </div>
    {% endif %}
{% endblock %}

templates/settings/links.html
<div class="settings-links">
    <ul>
        <li><a href="{% url 'settings:username' %}">ユーザ名</a></li>
        <li><a href="{% url 'settings:email' %}">メールアドレス</a></li>
        <li><a href="{% url 'settings:password' %}">パスワード</a></li>
        <li><a href="{% url 'settings:profile' %}">プロフィール</a></li>
        <li><a href="{% url 'settings:followees' %}">フォロー</a></li>
        <li><a href="{% url 'settings:followers' %}">フォロワー</a></li>
        <li><a href="{% url 'settings:newarticle' %}">新規記事の投稿</a></li>
        <li><a href="{% url 'settings:postedarticles' %}">記事の編集</a></li>
        <li><a href="{% url 'settings:deleteuser' %}">ユーザの削除</a></li>
    </ul>
</div>

templates/settings/relation.html
{% extends 'base/base.html' %}
{% load static %}

{% block extra_header %}
<link rel="stylesheet" href="{% static 'settings/links.css' %}">
<link rel="stylesheet" href="{% static 'settings/relation.css' %}">
<script src="https://code.jquery.com/jquery-3.6.0.js" integrity="sha256-H+K7U5CnXl1h5ywQfKtSj8PCmoN9aaq30gDh27Xc0jk=" crossorigin="anonymous" defer></script>
<script src="{% static 'users/follow.js' %}" defer></script>
{% endblock %}

{% block content %}
    <div class="settings-entire">
        {% include 'settings/links.html' %}

        <div class="followees">
            {% for relation in relation_list %}
                <div class="followee">
                    <ul>
                        <li class="followee-icon"><img src="/media/{{ relation.followee.icon }}" style="border-radius: 50px; width: 25px; height: 25px;"></li>
                        <li class="followee-username"><a href="{% url 'users:articles' relation.followee.username %}"> {{ relation.followee.username }} </a></li>

                        {% load is_follow %}
                        {% is_follow user relation.followee as follow_status %}
                        <form name="follow" action="{% url 'users:follow' relation.followee.username %}" method="POST">
                            {% csrf_token %}
                            {{ follow_form.follower }}
                            {% if follow_status %}
                                <input class="btn btn-info" name="follow_button" type="submit" value="フォロー中"/>
                            {% else %}
                                <input class="btn btn-info" name="follow_button" type="submit" value="フォローする"/>
                            {% endif %}
                        </form>

                        <li class="followee-profile"> {{ relation.followee.profile_message|slice:":30" }}... </li>
                    </ul>
                </div>
            {% endfor %}
        </div>
    </div>

    {% if relation_list %}
        <div class="pagination">
            <ul class="pagination">
                {% if page_obj.has_previous %}
                    <li class="page-item">
                        <a class="page-link" href="?page={{ page_obj.previous_page_number }}">
                            <span aria-hidden="true">&laquo;</span>
                        </a>
                    </li>
                {% endif %}
            
                {% for num in page_obj.paginator.page_range %}
                    {% if page_obj.number == num %}
                        <li class="page-item active"><a class="page-link" href="#!">{{ num }}</a></li>
                    {% else %}
                        <li class="page-item"><a class="page-link" href="?page={{ num }}">{{ num }}</a></li>
                    {% endif %}
                {% endfor %}
            
                {% if page_obj.has_next %}
                    <li class="page-item">
                        <a class="page-link" href="?page={{ page_obj.next_page_number }}">
                            <span aria-hidden="true">&raquo;</span>
                        </a>
                    </li>
                {% endif %}
            </ul> 
        </div>
    {% endif %}
{% endblock %}