articles/urls.py
from django.urls import path

from .views import ArticleView, ArticleListView, FavoriteArticleView, PostCommentView

app_name = 'articles'

urlpatterns = [
    path('', ArticleListView.as_view(), name='articles'),
    path('<int:pk>', ArticleView.as_view(), name='article'),
    path('<int:pk>/comments', PostCommentView.as_view(), name='comments'),
    path('<int:pk>/favorite', FavoriteArticleView.as_view(), name='favorite'),
]

users/urls.py
from django.urls import path
from .views import PostedArticleListView, FavoriteListView, FolloweeListView, FollowerListView, FollowView

app_name = 'users'

urlpatterns = [
    path('<str:username>', PostedArticleListView.as_view(), name='articles'),
    path('<str:username>/favorites', FavoriteListView.as_view(), name='favorites'),
    path('<str:username>/followees', FolloweeListView.as_view(), name='followees'),
    path('<str:username>/followers', FollowerListView.as_view(), name='followers'),
    path('<str:username>/follow', FollowView.as_view(), name='follow'),
]

articles/models.py
import datetime
from django.db import models
from django.contrib.auth import get_user_model

# Create your models here.

User = get_user_model()


class Tag(models.Model):
    tag = models.CharField(max_length=100, blank=False, null=False, unique=True)

    def __str__(self):
        return self.tag


class Article(models.Model):
    author = models.ForeignKey(User,
                               on_delete=models.CASCADE,
                               related_name='my_articles')
    title = models.CharField(max_length=1000)
    content = models.TextField(max_length=10000)
    create_date = models.DateField(default=datetime.date.today)
    tags = models.ManyToManyField(Tag, related_name='tagged_articles')
    favorite_users = models.ManyToManyField(User,
                                            blank=True,
                                            related_name='favorited_aritcles')

    class Meta:
        ordering = ['-create_date']

    def __str__(self):
        return self.title

    def is_favorited(self, user):
        """
        Userオブジェクトである引数userが記事をお気に入りに登録しているか否かの状態を返す

        Parameters
        ----------
        user : User
            お気に入りしているユーザ(favaorite_users)の中に含まれているか確認する対象

        Raises
        ------
        TypeError
            userオブジェクトがUserクラスのインスタンスで無い場合に発生

        Returns
        -------
        False : bool
            userが認証されていないユーザの場合もしくは,favorite_usersに含まれていない場合

        True : bool
            userが認証されており,かつfavorite_usersに含まれている
        """
        if (not user.is_authenticated
                or not self.favorite_users.filter(pk=user.pk).exists()):
            return False
        return True


class Comment(models.Model):
    article = models.ForeignKey(Article, on_delete=models.CASCADE)
    comment_author = models.ForeignKey(User, on_delete=models.CASCADE)
    content = models.TextField(max_length=1000)
    create_data = models.DateField(auto_now_add=True)

    def __str__(self):
        return 'comment by {} at {}'.format(self.comment_author,
                                            self.create_data)

articles/forms.py
from django import forms
from django.contrib.auth import get_user_model

from .models import Comment, Tag

User = get_user_model()


class SearchArticleForm(forms.Form):
    keyword = forms.CharField(max_length=100, required=False)

    all_article_tag = Tag.objects.order_by('pk').all()
    TAG_CHOICES = [(article_tag.pk, article_tag.tag)
                   for article_tag in all_article_tag]
    TAG_CHOICES.insert(0, ('all', '全てのタグ'))
    tag = forms.ChoiceField(choices=TAG_CHOICES, required=False)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs['class'] = 'form-control'


class PostCommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('content',)
        widgets = {
            'content': forms.Textarea(attrs={'rows': 5, 'cols': 30}),
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs['class'] = 'mt-2 mb-3 font-weight-normal'


class FavoriteArticleForm(forms.Form):
    """
    記事をお気にいりに登録する際にユーザ名を送信するためのフォーム

    Parameters
    ----------
    username : str
        ユーザ名を表す文字列
    """
    username = forms.CharField(max_length=30, required=True)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['username'].widget = forms.HiddenInput()

    def clean_username(self):
        username = self.cleaned_data['username']

        # ユーザ名に一致するユーザが存在しない場合はバリデーションエラーを発生させる
        if not User.objects.filter(username=username).exists():
            raise forms.ValidationError("user is not exist")

        return username

articles/views.py
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.exceptions import ObjectDoesNotExist
from django.db.models import Q
from django.http import Http404, HttpResponseBadRequest
from django.http.response import JsonResponse
from django.shortcuts import get_object_or_404, redirect
from django.views.generic import FormView, CreateView, DetailView, ListView
from django.shortcuts import render


from users.forms import FollowForm
from .forms import FavoriteArticleForm, PostCommentForm, SearchArticleForm
from .models import Article, Tag

# Create your views here.

User = get_user_model()


class ArticleListView(ListView):
    template_name = 'articles/articles.html'
    model = Article
    paginate_by = 5

    def fetch_get_parameter(self, parameter_name):
        if type(parameter_name) is not str or parameter_name == "":
            raise KeyError("request url is not include {}".format(parameter_name))

        if parameter_name not in self.request.GET:
            raise KeyError("request url is not include {}".format(parameter_name))

        return self.request.GET.get(parameter_name)

    def get_queryset(self):
        queryset = super().get_queryset()

        # キーワードをURLパラメータから抽出
        try:
            keyword = self.fetch_get_parameter("keyword")
            queryset = queryset.filter(Q(title__contains=keyword)
                                       | Q(content__contains=keyword))
        except KeyError:
            pass

        # tagをURLパラメータから抽出
        try:
            tag_pk = self.fetch_get_parameter("tag")
        except KeyError:
            # タグが存在しない場合は現時点での条件のクエリセットを返す
            return queryset

        # tagがallである場合は現時点でのクエリセットを返す
        if tag_pk == 'all':
            return queryset

        # タグオブジェクトを取得する
        # 存在しないタグの場合は,存在しないタグのpkを指定したクエリセットを返す
        try:
            tag = Tag.objects.get(pk__in=tag_pk)
        except ValueError:
            queryset = queryset.filter(tags=-1)
            return queryset
        except ObjectDoesNotExist:
            queryset = queryset.filter(tags=-1)
            return queryset

        queryset = queryset.filter(tags=tag)
        return queryset

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        # 記事一覧を取得する,検索結果が何も無い場合は 404 を返す
        article_list = context['article_list']
        if article_list.first() is None:
            raise Http404('指定したキーワードとタグを含む記事は存在しませんでした')

        context['form'] = SearchArticleForm
        return context


class ArticleView(DetailView):
    template_name = 'articles/article.html'
    model = Article

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        context['comment_form'] = PostCommentForm

        context['favorite_form'] = FavoriteArticleForm
        # 既にお気に入り登録しているか否かでボタンに表示する値ととお気に入りフォームのvalue
        # に設定される状態を示す文字列を決定する
        context['favorite_button_value'] = 'お気に入り済み' \
            if self.object.is_favorited(self.request.user) else 'お気に入りに追加'
        context['favorite_status'] = 'favorited' \
            if self.object.is_favorited(self.request.user) else 'notfavorited'

        # 認証されていないユーザの場合は現時点のデータを返す
        if not self.request.user.is_authenticated:
            return context

        # 認証ユーザの場合はFavoriteArticleFormに現在のユーザ名を設定
        username = self.request.user.username
        initial_form_dict = dict(follower=username)
        follow_form = FollowForm(initial=initial_form_dict)
        context['follow_form'] = follow_form

        return context

    def get(self, request, *args, **kwargs):
        if not self.request.user.is_authenticated:
            return super().get(request, *args, **kwargs)

        # 認証ユーザの場合はFavoriteArticleFormに現在のユーザ名を設定
        username = self.request.user.username
        initial_form_dict = dict(username=username)
        favorite_form = FavoriteArticleForm(request.GET or None,
                                            initial=initial_form_dict)
        self.object = self.get_object()
        context = self.get_context_data(object=self.object)
        context['favorite_form'] = favorite_form

        return render(request, self.template_name, context)


class PostCommentView(LoginRequiredMixin, CreateView):
    template_name = ''
    form_class = PostCommentForm

    def form_valid(self, form):
        article_id = self.kwargs['pk']
        article = get_object_or_404(Article, pk=article_id)
        author = User.objects.get(pk=self.request.user.pk)

        comment = form.save(commit=False)
        comment.article = article
        comment.comment_author = author
        comment.save()
        return redirect('articles:article', pk=article_id)

    # GETリクエストされた場合はとりあえずリダイレクトさせる
    def get(self, request, *args, **kwargs):
        article_id = self.kwargs['pk']
        return redirect('articles:article', pk=article_id)


class FavoriteArticleView(LoginRequiredMixin, FormView):
    form_class = FavoriteArticleForm
    template_name = 'base/blank.html'

    def post(self, request, *args, **kwargs):
        form = self.get_form()
        if form.is_valid():
            return self.form_valid(form)
        else:
            return self.form_invalid(form)

    def form_valid(self, form):
        # Ajaxリクエストでない場合はBadRequestを返す
        if not self.request.is_ajax:
            raise HttpResponseBadRequest()

        # 送信されてきたユーザ名を取得し,送信してきたユーザと同じであるか確認する
        username = form.cleaned_data['username']
        user = User.objects.get(username=username)
        if self.request.user != user:
            raise HttpResponseBadRequest()

        # 更新対象のArticleオブジェクトを取得
        article_id = self.kwargs['pk']
        article = get_object_or_404(Article, pk=article_id)

        # お気に入りユーザとして登録していない場合は追加を行い,
        # 既にお気に入りユーザとして登録している場合は削除を行い,状態を保存して更新する
        if article.favorite_users.filter(username=username).exists():
            article.favorite_users.remove(user)
            status = 'notfavorited'
        else:
            article.favorite_users.add(user)
            status = 'favorited'
        article.save()

        # 処理の結果を格納するJSONオブジェクトを返す
        json_response = {
            'data': {
                'status': status
            }
        }
        return JsonResponse(json_response)

    def form_invalid(self, form):
        # 正しく無いデータが送信されてきた場合は500を返す
        return JsonResponse({}, status=500)

templates/articles/article.html
{% extends 'base/base.html' %}
{% load static %}

{% block extra_header %}
    <link rel="stylesheet" href="{% static 'articles/article.css' %}">
    {% if user.is_authenticated %}
        <script src="https://code.jquery.com/jquery-3.6.0.js" integrity="sha256-H+K7U5CnXl1h5ywQfKtSj8PCmoN9aaq30gDh27Xc0jk=" crossorigin="anonymous" defer></script>
        <script src="{% static 'users/follow.js' %}" defer></script>
    {% endif %}
{% endblock %}

{% block content %}
    <div class="article-entire">
        <div class="article-author-profile">
            <ul>
                <li class="author-icon"><img src="{{ MEDIA_URL }}{{ article.author.icon }}"></li>
                <li class="author-name"><a href="{% url 'users:articles' article.author.username %}">{{ article.author.username }}</a></li>
            </ul>
        </div>

        <main class="article-content">
            <div class="article-favorite">
                {% if user.is_authenticated %}
                    <script src="https://code.jquery.com/jquery-3.6.0.js" integrity="sha256-H+K7U5CnXl1h5ywQfKtSj8PCmoN9aaq30gDh27Xc0jk=" crossorigin="anonymous"></script>
                    <script src="{% static 'articles/favorite.js' %}" defer></script>
                    <form name="favorite" action="{% url 'articles:favorite' article.pk %}" method="POST">
                        {% csrf_token %}
                        {{ favorite_form.username }}
                        <input id="favorite_button" type="submit" value="{{ favorite_button_value }}" message-status="{{ favorite_status }}" style="border:0px; color: white; background-color:orange"/>
                    </form>
                {% endif %}
            </div>

            <div class="article-tags">
                <b class="article-tags-header">Tags:</b>
                <ul>
                    {% for tag in article.tags.all %}
                        <li><a href="{% url 'articles:articles'%}?tag={{ tag.pk }}">#{{ tag }}</a></li>
                    {% endfor %}
                </ul>    
            </div>


            <div class="article-title">
                <b class="title">Title:</b>
                <p class="title-sentence">{{ article.title }}</p>
                <p class="create-date">{{ article.create_date }}</p>
            </div>


            <div class="article-sentence">
                <b class="article-sentence-header">Sentence:</b>
                <div class="sentence">{{ article.content }}</div>
            </div>

            <div class="article-comments">
                <div class="comment-post-form">
                    {% if user.is_authenticated %}
                        <form class="comment-postform" action="{% url 'articles:comments' article.pk %}"  method="POST">
                            {% csrf_token %}
                            {{ comment_form.non_field_errors }}
                            {% for comment_form_field in comment_form %}
                                <div class="form-group">
                                    {{ comment_form_field }}
                                    {{ comment_form_field.errors }}
                                </div>
                            {% endfor %}
                            <input class="btn btn-outline-success my-2 my-sm-0" type="submit" value="コメント投稿"/>
                        </form>
                    {% else %}
                        <p class="alert alert-info">⚠️ログインするとコメントする事が出来ます</p>
                    {% endif %}
                </div>

                <div class="comments">
                    {% for comment in article.comment_set.all %}
                        <ul class="article-comment">
                            <li class="comment-author-icon"><img src="{{ MEDIA_URL }}{{ comment.comment_author.icon }}" style="border-radius: 50px; width: 25px; height: 25px;"> <a href="{% url 'users:articles' comment.comment_author.username %}">{{ comment.comment_author.username }}</a> {{ comment.create_data }}</li>
                            <li class="comment-content">{{ comment.content }}</li>
                        </ul>
                    {% endfor %}
                </div>
            </div>
        </main>
    </div>
{% endblock %}

templates/articles/articles.html
{% extends 'base/base.html' %}
{% load static %}

{% block extra_header %}
    <link rel="stylesheet" href="{% static 'articles/articles.css' %}">
{% endblock %}

{% block content %}
    <div class="search-form">
        <form class="form-inline my-2 my-lg-0" action="" method="GET">
            {{ form.non_field_errors }}
            <ul>
                <li>{{ form.tag }}</li>
                <li>{{ form.keyword }}</li>
                <li><button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button></li>
            </ul>
        </form>
    </div>

    <div class="article-list-area">
        <ul>
            {% for article in article_list %}
                <ul class="article">
                    <li class="author-info"><img src='{{ MEDIA_URL }}{{ article.author.icon }}' style='border-radius: 50px; width: 25px; height: 25px;'> <a href="{% url 'users:articles' article.author.username %}">{{ article.author.username }}</a>が{{ article.create_date }}に投稿</li>
                    <li class="article-title"><a href='{% url "articles:article" article.pk %}'> {{ article.title }} </a></li>
                    <li class="article-content">{{ article.content|slice:":30" }} ... </li>
                </ul>
            {% endfor %}
        </ul>

        <ul class="pagination">
            {% if page_obj.has_previous %}
                <li class="page-item">
                    <a class="page-link" href="?page={{ page_obj.previous_page_number }}">
                        <span aria-hidden="true">&laquo;</span>
                    </a>
                </li>
            {% endif %}
        
            {% for num in page_obj.paginator.page_range %}
                {% if page_obj.number == num %}
                    <li class="page-item active"><a class="page-link" href="#!">{{ num }}</a></li>
                {% else %}
                    <li class="page-item"><a class="page-link" href="?page={{ num }}">{{ num }}</a></li>
                {% endif %}
            {% endfor %}
        
            {% if page_obj.has_next %}
                <li class="page-item">
                    <a class="page-link" href="?page={{ page_obj.next_page_number }}">
                        <span aria-hidden="true">&raquo;</span>
                    </a>
                </li>
            {% endif %}
        </ul>    
    </div>
{% endblock %}